# Generated by Django 3.2.19 on 2023-05-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230521_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='quantity',
            new_name='amount',
        ),
    ]
