# Generated by Django 3.2.19 on 2023-05-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230521_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavorites',
        ),
    ]
