# Generated by Django 3.2.19 on 2023-05-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
